DELIMITER //
CREATE TRIGGER AFTER_BILL_ITEM_INSERT 
AFTER INSERT
ON BILL_COMMODITY
FOR EACH ROW 
BEGIN
	DECLARE V_USER_ID INT;
    
	UPDATE COMMODITIES SET QUANTITY = QUANTITY + NEW.SUPPLIED_AMOUNT WHERE ID = NEW.COMMODITY_ID;
    
    SELECT USER_ID INTO V_USER_ID FROM BILLS WHERE ID=NEW.BILL_ID;
    
    INSERT INTO DAILY_LOGS VALUES (NULL,V_USER_ID,'RECEIVED',NEW.COST,NOW(),CONCAT('Stock Received: ',NEW.COMMODITY_NAME),NOW(),NOW());
END //
DELIMITER ;

DELIMITER //
CREATE TRIGGER AFTER_PAYMENT_INSERT
AFTER INSERT 
ON PAYMENTS 
FOR EACH ROW 
BEGIN 
	DECLARE V_USER_ID INT;
    
	UPDATE BILLS SET PAID_AMOUNT = PAID_AMOUNT + NEW.AMOUNT WHERE ID = NEW.BILL_ID;
    
    UPDATE BILLS 
    SET STATUS = CASE
		WHEN PAID_AMOUNT >= TOTAL_AMOUNT THEN 'PAID'
        WHEN PAID_AMOUNT > 0 AND PAID_AMOUNT < TOTAL_AMOUNT THEN 'PARTIAL'
        ELSE 'UNPAID'
	END
    WHERE ID=NEW.BILL_ID;
    
    SELECT USER_ID INTO V_USER_ID FROM BILLS WHERE ID=NEW.BILL_ID;
    
    INSERT INTO DAILY_LOGS VALUES (NULL,V_USER_ID,'PAID',NEW.AMOUNT,NOW(),'Payment Recorded', NOW(),NOW());
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE RECORD_SECURE_PAYMENT(
	IN P_PAYMENT_ID INT, 
    IN P_BILL_ID INT,
    IN P_AMOUNT NUMERIC(12,2),
    IN P_MODE VARCHAR(10)
)
PROC_BODY: BEGIN
	DECLARE V_TOTAL NUMERIC(12,2);
    DECLARE V_PAID NUMERIC(12,2);
    DECLARE V_PENDING NUMERIC(12,2);
    START TRANSACTION;
    SELECT TOTAL_AMOUNT, PAID_AMOUNT INTO V_TOTAL,V_PAID FROM BILLS WHERE ID=P_BILL_ID;
    SET V_PENDING = V_TOTAL - V_PAID;
    IF P_AMOUNT <=0  THEN
		ROLLBACK;
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'PAYMNET AMOUNT MUST BE GREATER THAN ZERO';
        LEAVE PROC_BODY;
	END IF;
    IF P_AMOUNT > V_PENDING THEN
        ROLLBACK;
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'PAYMENT EXCEEDS PENDING AMOUNT';
    END IF;
    INSERT INTO PAYMENTS(ID,BILL_ID,AMOUNT, PAYMENT_MODE)
    VALUES (P_PAYMENT_ID,P_BILL_ID,P_AMOUNT,P_MODE);
    
    COMMIT;
END //
DELIMITER ;

DELIMITER //
CREATE FUNCTION EVALUATE_STOCK_STATUS(CURRENT_STOCK NUMERIC(10,2),MIN_STOCK NUMERIC(10,2))
RETURNS VARCHAR(15)
DETERMINISTIC
BEGIN 
	DECLARE STATUS_LABEL VARCHAR(15);
	IF CURRENT_STOCK =0 THEN 
		SET STATUS_LABEL = 'CRITICAL';
	ELSEIF CURRENT_STOCK < MIN_STOCK THEN 
		SET STATUS_LABEL='LOW';
	ELSE
		SET STATUS_LABEL = 'OK';
	END IF;
    RETURN STATUS_LABEL;
END //
DELIMITER ;

CREATE VIEW VIEW_LOW_STOCK_ALERTS AS 
SELECT 
    USER_ID,
    COMMODITY_NAME,
    QUANTITY AS CURR_STOCK,
    MIN_QUANTITY AS THRESHOLD,
    (MIN_QUANTITY - QUANTITY) AS COMPUTED_SHORTAGE,
    EVALUATE_STOCK_STATUS(QUANTITY, MIN_QUANTITY) AS STOCK_STATUS
FROM COMMODITIES
WHERE QUANTITY < MIN_QUANTITY;

CREATE VIEW VIEW_PAYMENT_PRIORITY_LIST AS
SELECT 
    B.USER_ID,
    B.ID AS BILL_ID,
    V.VENDOR_NAME,
    (B.TOTAL_AMOUNT - B.PAID_AMOUNT) AS PENDING_DUE,
    V.TOLERANCE_LEVEL
FROM BILLS B
JOIN VENDORS V ON B.VENDOR_ID = V.ID
WHERE B.STATUS != 'PAID'
ORDER BY PENDING_DUE DESC;