-- ============================================
-- USER & BUSINESS PROFILE MANAGEMENT
-- ============================================

-- RETRIEVE THE FULL USER RECORD TO VERIFY LOGIN CREDENTIALS
SELECT * 
FROM USERS
WHERE EMAIL = 'vedant@gmail.com';

-- BUSINESS PROFILE FOR A SPECIFIC USER
SELECT BUSINESS_NAME
FROM PROFILES
WHERE USER_ID = 2;

-- UPDATE BUSINESS PROFILE DETAILS
UPDATE PROFILES
SET BUSINESS_NAME = 'Rahul Enterprise',
    PHONE_NUMBER = '9876543240'
WHERE USER_ID = 1;


-- ============================================
-- VENDOR MANAGEMENT
-- ============================================

-- LIST ALL SUPPLIERS REGISTERED UNDER A SPECIFIC BUSINESS
SELECT VENDOR_NAME, PHONE_NUMBER, TOLERANCE_LEVEL
FROM VENDORS
WHERE USER_ID = 2;

-- MODIFY CREDIT LIMIT FOR A SPECIFIC VENDOR
UPDATE VENDORS
SET TOLERANCE_AMOUNT = 7500,
    TOLERANCE_LEVEL = 'HIGH'
WHERE ID = 1;

-- COUNT TOTAL NUMBER OF REGISTERED SUPPLIERS FOR A BUSINESS
SELECT COUNT(ID) AS VENDOR_COUNT
FROM VENDORS
WHERE USER_ID = 1;

-- FIND ALL VENDORS WHO SUPPLY A SPECIFIC COMMODITY
SELECT COMMODITY_ID
FROM VENDOR_COMMODITY
WHERE VENDOR_ID = 1;


-- ============================================
-- INVENTORY MANAGEMENT
-- ============================================

-- SHOW ALL INVENTORY ITEMS CURRENTLY TRACKED
SELECT COMMODITY_NAME, QUANTITY, UNIT, MIN_QUANTITY
FROM COMMODITIES
WHERE USER_ID = 1;

-- UPDATE TOTAL STOCK FOR A SPECIFIC COMMODITY
UPDATE COMMODITIES
SET QUANTITY = 75
WHERE ID = 1;

-- FIND INVENTORY ITEMS THAT HAVE NEVER BEEN USED IN ANY BILL
SELECT COMMODITY_NAME
FROM COMMODITIES
WHERE ID NOT IN (
    SELECT COMMODITY_ID
    FROM BILL_COMMODITY
);

-- FIND COMMODITIES BELOW MINIMUM STOCK AND THEIR RECOMMENDED VENDORS
SELECT C.COMMODITY_NAME,
       C.QUANTITY AS CURRENT_STOCK,
       C.MIN_QUANTITY,
       V.VENDOR_NAME AS RECOMMENDED_VENDOR
FROM COMMODITIES C
JOIN VENDOR_COMMODITY VC ON C.ID = VC.COMMODITY_ID
JOIN VENDORS V ON VC.VENDOR_ID = V.ID
WHERE C.QUANTITY < C.MIN_QUANTITY;


-- ============================================
-- BILL MANAGEMENT
-- ============================================

-- RETRIEVE ALL BILLS FOR A SPECIFIC USER
SELECT ID, TOTAL_AMOUNT, STATUS, BILL_DATE
FROM BILLS
WHERE USER_ID = 1;

-- LIST ALL INDIVIDUAL ITEMS CONTAINED WITHIN A SPECIFIC BILL
SELECT COMMODITY_NAME, SUPPLIED_AMOUNT, UNIT, COST
FROM BILL_COMMODITY
WHERE BILL_ID = 2;


-- ============================================
-- PAYMENT MANAGEMENT
-- ============================================

-- TRACK ALL MONEY PAID OUT TO A SPECIFIC VENDOR
SELECT P.BILL_ID, P.AMOUNT, P.PAYMENT_MODE
FROM PAYMENTS P
JOIN BILLS B ON P.BILL_ID = B.ID
WHERE B.VENDOR_ID = 2;

-- RETRIEVE THE FINANCIAL ACTIVITY LOGS FOR A SPECIFIC BUSINESS
SELECT LOG_TYPE, AMOUNT, NOTE
FROM DAILY_LOGS
WHERE USER_ID = 1;


-- ============================================
-- REPORTS & BUSINESS ANALYTICS
-- ============================================

-- WHICH VENDORS SHOULD WE PRIORITIZE PAYING FIRST?
-- SORT BY CREDIT TOLERANCE LEVEL, THEN BY HIGHEST PENDING DEBT
SELECT V.VENDOR_NAME,
       V.TOLERANCE_LEVEL,
       SUM(B.TOTAL_AMOUNT - B.PAID_AMOUNT) AS PENDING_AMOUNT
FROM VENDORS V
JOIN BILLS B ON V.ID = B.VENDOR_ID
WHERE B.STATUS != 'PAID'
GROUP BY V.VENDOR_NAME, V.TOLERANCE_LEVEL
ORDER BY
    CASE
        WHEN V.TOLERANCE_LEVEL = 'LOW' THEN 1
        WHEN V.TOLERANCE_LEVEL = 'MEDIUM' THEN 2
        ELSE 3
    END,
    PENDING_AMOUNT DESC;

-- FIND WHICH USER HAS THE HIGHEST TOTAL PENDING DUE
SELECT U.USER_NAME,
       SUM(B.TOTAL_AMOUNT - B.PAID_AMOUNT) AS TOTAL_PENDING
FROM USERS U
JOIN BILLS B ON U.USER_ID = B.USER_ID
GROUP BY U.USER_NAME
ORDER BY TOTAL_PENDING DESC
LIMIT 1;

-- CALCULATE TOTAL PAYMENT MADE TO EACH VENDOR
SELECT V.VENDOR_NAME,
       SUM(P.AMOUNT) AS TOTAL_RECEIVED
FROM PAYMENTS P
JOIN BILLS B ON P.BILL_ID = B.ID
JOIN VENDORS V ON B.VENDOR_ID = V.ID
GROUP BY V.VENDOR_NAME
ORDER BY TOTAL_RECEIVED DESC;

-- SHOW TOTAL RECEIVED AND PAID AMOUNTS FOR EACH BUSINESS
SELECT USER_ID,
       LOG_TYPE,
       SUM(AMOUNT) AS TOTAL_AMOUNT
FROM DAILY_LOGS
GROUP BY USER_ID, LOG_TYPE
ORDER BY USER_ID;

-- FIND THE VENDOR SUPPLYING THE HIGHEST NUMBER OF DIFFERENT COMMODITIES
SELECT V.VENDOR_NAME,
       COUNT(VC.COMMODITY_ID) AS TOTAL_COMMODITIES
FROM VENDORS V
JOIN VENDOR_COMMODITY VC ON V.ID = VC.VENDOR_ID
GROUP BY V.VENDOR_NAME
ORDER BY TOTAL_COMMODITIES DESC
LIMIT 1;