DROP DATABASE IF EXISTS SMS_DB;
CREATE DATABASE SMS_DB;
USE SMS_DB;

CREATE TABLE USERS(
	USER_ID INT PRIMARY KEY,
    USER_NAME VARCHAR(36) NOT NULL,
    EMAIL VARCHAR(256) UNIQUE NOT NULL
);

CREATE TABLE PROFILES(
	USER_ID INT PRIMARY KEY,
    BUSINESS_NAME VARCHAR(50) NOT NULL,
    PHONE_NUMBER VARCHAR(15),
    ADDRESS VARCHAR(255),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE VENDORS(
	ID INT PRIMARY KEY,
    USER_ID INT NOT NULL,
    VENDOR_NAME VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(15),
    TOLERANCE_AMOUNT NUMERIC(12,2) CHECK (TOLERANCE_AMOUNT >=0),
    TOLERANCE_LEVEL ENUM('LOW','MEDIUM','HIGH') NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE COMMODITIES(
	ID INT PRIMARY KEY,
    USER_ID INT NOT NULL,
    COMMODITY_NAME VARCHAR(255) NOT NULL,
    QUANTITY NUMERIC(10,2) NOT NULL DEFAULT 0.0 CHECK (QUANTITY>=0),
	UNIT VARCHAR(50) NOT NULL,
    MIN_QUANTITY NUMERIC(10,2) NOT NULL DEFAULT 0.0 CHECK (MIN_QUANTITY >= 0),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE VENDOR_COMMODITY(
	VENDOR_ID INT NOT NULL,
    COMMODITY_ID INT NOT NULL,
    PRIMARY KEY (VENDOR_ID,COMMODITY_ID),
    FOREIGN KEY (VENDOR_ID) REFERENCES VENDORS(ID) ON DELETE CASCADE,
    FOREIGN KEY (COMMODITY_ID) REFERENCES COMMODITIES(ID) ON DELETE CASCADE
);

CREATE TABLE BILLS(
	ID INT PRIMARY KEY,
    VENDOR_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    TOTAL_AMOUNT NUMERIC(12,2) NOT NULL CHECK (TOTAL_AMOUNT >=0),
    PAID_AMOUNT NUMERIC(12,2) NOT NULL DEFAULT 0.0 CHECK (PAID_AMOUNT >=0 ),
    STATUS ENUM('UNPAID','PARTIAL','PAID') NOT NULL DEFAULT 'UNPAID',
    BILL_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CHECK (PAID_AMOUNT <= TOTAL_AMOUNT),
    FOREIGN KEY (VENDOR_ID) REFERENCES VENDORS(ID) ON DELETE RESTRICT,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);	

CREATE TABLE BILL_COMMODITY(
	ID INT PRIMARY KEY,
    BILL_ID INT NOT NULL,
    COMMODITY_ID INT NOT NULL,
    COMMODITY_NAME VARCHAR(255) NOT NULL,
    -- NAME IS STORED BECUASE SUPPOSE IF 6 MONTHS LATER IF THE NAME OF COMMODITY IS CHANGED THEN TOO IT WILL HAVE PROPER BILLING
    SUPPLIED_AMOUNT NUMERIC(10,2) NOT NULL CHECK (SUPPLIED_AMOUNT >=0),
    UNIT VARCHAR(50) NOT NULL,
    COST NUMERIC(12,2) NOT NULL CHECK (COST >= 0),
    FOREIGN KEY (BILL_ID) REFERENCES BILLS(ID) ON DELETE CASCADE,
    FOREIGN KEY (COMMODITY_ID) REFERENCES COMMODITIES(ID) ON DELETE RESTRICT
);

CREATE TABLE PAYMENTS(
	ID INT PRIMARY KEY,
    BILL_ID INT NOT NULL,
    AMOUNT NUMERIC(12,2) NOT NULL CHECK (AMOUNT >=0 ),
    PAYMENT_MODE ENUM('CASH','UPI') NOT NULL,
    PAYMENT_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BILL_ID) REFERENCES BILLS(ID) ON DELETE CASCADE
);

CREATE TABLE DAILY_LOGS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    LOG_TYPE ENUM('RECEIVED','PAID') NOT NULL,
    AMOUNT NUMERIC(12,2) NOT NULL CHECK (AMOUNT >= 0),
    LOG_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NOTE VARCHAR(255	),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);
